[package]
name = "logic"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "sandbox" # приложение, где всё подряд
path = "src/bin/sandbox.rs"

[[bin]]
name = "game_guessing"
path = "src/bin/game_guessing.rs"

[[bin]]
name = "app1"
path = "src/bin/app1.rs"

[dependencies]
rand = "0.9.2"
